/**
 * Audit generator for the pre-retirement `escalates` fixture.
 *
 * Writes `escalates-v3.db`: a schema-v3 Command Center whose `factory` canvas
 * was authored while agent -> requests `escalates` was a legal verb. It holds
 * two escalates edges (one masked with the `request.escalate` port), an
 * agent -> agent `messages` edge whose mask also names that retired port, and
 * an unrelated `works` edge that must come through untouched.
 *
 * Frozen history: this build cannot regenerate the stored database.
 */
import type { CanvasDoc } from "../../../src/shared/canvas";

const agent = (id: string, bindingId: string) => ({
  id,
  type: "text" as const,
  text: id,
  x: 0,
  y: 0,
  width: 240,
  height: 72,
  ether: {
    entity: { kind: "agent", name: `local:${id}` },
    terminal: {
      bindingId,
      launch: { kind: "harness", argv: ["codex"] },
      harness: "codex",
    },
    host: "local",
  },
});

const sink = (id: string, kind: string, x: number) => ({
  id,
  type: "text" as const,
  text: id,
  x,
  y: 200,
  width: 200,
  height: 80,
  ether: { entity: { kind } },
});

export const ESCALATES_FIXTURE_DOC = {
  nodes: [
    agent("agent", "fixture-escalates-agent"),
    agent("peer", "fixture-escalates-peer"),
    sink("tasks", "task", 0),
    sink("requests", "requests", 300),
    sink("requests-2", "requests", 600),
  ],
  edges: [
    { id: "claim-edge", fromNode: "agent", toNode: "tasks", ether: { verb: "works" } },
    { id: "raise", fromNode: "agent", toNode: "requests", ether: { verb: "escalates" } },
    {
      id: "raise-masked",
      fromNode: "peer",
      toNode: "requests-2",
      label: "ask the operator",
      ether: { verb: "escalates", mask: ["request.escalate", "msg.list"] },
    },
    {
      id: "mail",
      fromNode: "agent",
      toNode: "peer",
      ether: { verb: "messages", mask: ["msg.send", "request.escalate"] },
    },
  ],
} as unknown as CanvasDoc;

/** Stored v3 bytes are immutable; current migrations cannot recreate them. */
export const generateEscalatesFixture = async (_path: string): Promise<void> => {
  throw new Error("This fixture is frozen history and cannot be regenerated by this build.");
};
