/**
 * Load precompiled plugin package payloads (no runtime packager / no Bun).
 *
 * Payloads are frozen JSON under ./payloads/, regenerated by maintainers with:
 *   bun scripts/precompile-vellum-plugin.ts
 *
 * @skastr0/prism-packager requires Bun and must never load in Electron Node.
 */

import { Effect, Schema } from "effect";
import type { FleetPluginTarget } from "./harness-targets";
import { isFleetPluginTarget } from "./harness-targets";
import type { HarnessId, HarnessScope, PackageResult } from "./types";

// Static imports — electron-vite bundles JSON into main (no runtime Bun, no fs path).
import claudeCodePayload from "./payloads/claude-code.json";
import codexCliPayload from "./payloads/codex-cli.json";
import grokPayload from "./payloads/grok.json";
import hermesPayload from "./payloads/hermes.json";

export class PackageCompileError extends Schema.TaggedError<PackageCompileError>()(
  "PackageCompileError",
  {
    pluginPath: Schema.String,
    target: Schema.String,
    message: Schema.String,
  },
) {}

export type CompilePluginPackageOptions = {
  readonly pluginPath: string;
  readonly target: HarnessId;
  readonly scope?: HarnessScope;
  readonly out?: string;
  readonly projectPath?: string;
  readonly generatorVersion?: string;
  readonly force?: boolean;
};

type PrecompiledPayload = {
  readonly schema: string;
  readonly target: string;
  readonly packageId: string;
  readonly packageRoot: string;
  readonly planRoot: string;
  readonly operations: PackageResult["operations"];
  readonly compileFiles: PackageResult["compileFiles"];
  readonly compileRegions: PackageResult["compileRegions"];
  readonly activationPath?: string;
  readonly manifestPath?: string;
};

const PAYLOADS: Readonly<Record<FleetPluginTarget, PrecompiledPayload>> = {
  "claude-code": claudeCodePayload as PrecompiledPayload,
  "codex-cli": codexCliPayload as PrecompiledPayload,
  grok: grokPayload as PrecompiledPayload,
  hermes: hermesPayload as PrecompiledPayload,
};

const toPackageResult = (payload: PrecompiledPayload): PackageResult => ({
  target: payload.target,
  packageId: payload.packageId,
  packageRoot: payload.packageRoot,
  planRoot: payload.planRoot,
  ...(payload.activationPath !== undefined
    ? { activationPath: payload.activationPath }
    : {}),
  ...(payload.manifestPath !== undefined
    ? { manifestPath: payload.manifestPath }
    : {}),
  operations: payload.operations,
  compileFiles: payload.compileFiles,
  compileRegions: payload.compileRegions ?? [],
});

/**
 * Resolve a precompiled package for one harness target.
 * `pluginPath` is accepted for API compatibility but not used (payload is frozen).
 */
export const compilePluginPackage = (
  opts: CompilePluginPackageOptions,
): Effect.Effect<PackageResult, PackageCompileError> => {
  if (!isFleetPluginTarget(opts.target)) {
    return Effect.fail(
      new PackageCompileError({
        pluginPath: opts.pluginPath,
        target: opts.target,
        message: `no precompiled payload for harness "${opts.target}" — run bun scripts/precompile-vellum-plugin.ts after adding the target`,
      }),
    );
  }
  const payload = PAYLOADS[opts.target];
  if (!payload || payload.schema !== "vellum.plugin-package/v1") {
    return Effect.fail(
      new PackageCompileError({
        pluginPath: opts.pluginPath,
        target: opts.target,
        message: `corrupt or missing precompiled payload for "${opts.target}"`,
      }),
    );
  }
  return Effect.succeed(toPackageResult(payload));
};
