// Extracts the CodexBar.app provider-icon set into a vendored TS data module.
// One-shot generator: bun scripts/extract-provider-marks.ts [resources-dir]
// Output: src/renderer/lib/provider-marks.generated.ts (committed; no runtime
// dependency on CodexBar.app).
//
// Only simple <path d="…"> glyphs are extracted (single or multi-path, with
// optional fill-rule). Paths carrying transforms are skipped and reported so
// the curated facade can hand-pick a different mark for that provider.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const RESOURCES =
  process.argv[2] ?? "/Applications/CodexBar.app/Contents/Resources";
const OUT = "src/renderer/lib/provider-marks.generated.ts";

interface MarkData {
  readonly viewBox: string;
  readonly paths: ReadonlyArray<string>;
  readonly fillRule?: "evenodd";
}

const files = readdirSync(RESOURCES)
  .filter((f) => /^ProviderIcon-.+\.svg$/.test(f))
  .sort();

const marks: Record<string, MarkData> = {};
const skipped: Array<{ id: string; reason: string }> = [];

for (const file of files) {
  const id = file.replace(/^ProviderIcon-/, "").replace(/\.svg$/, "");
  const svg = readFileSync(join(RESOURCES, file), "utf8");

  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) {
    skipped.push({ id, reason: "no viewBox" });
    continue;
  }

  const pathTags = svg.match(/<path\b[^>]*>/g) ?? [];
  const paths: string[] = [];
  let evenodd = false;
  let hasTransform = false;
  for (const tag of pathTags) {
    if (/\btransform=/.test(tag)) {
      hasTransform = true;
      continue;
    }
    const d = tag.match(/\bd="([^"]+)"/)?.[1];
    if (!d) continue;
    if (/fill-rule="evenodd"/.test(tag)) evenodd = true;
    paths.push(d);
  }
  if (hasTransform) {
    skipped.push({ id, reason: "path transform(s) — needs manual baking" });
    continue;
  }
  if (paths.length === 0) {
    skipped.push({ id, reason: "no usable path data" });
    continue;
  }
  marks[id] = {
    viewBox,
    paths,
    ...(evenodd ? { fillRule: "evenodd" as const } : {}),
  };
}

const header = `// GENERATED by scripts/extract-provider-marks.ts — do not edit by hand.
// Source: the local CodexBar.app provider-icon set (monochrome marks, fills
// normalized away; consumers assign hue). Regenerate with:
//   bun scripts/extract-provider-marks.ts
`;

const body = `${header}
export interface ProviderMarkData {
  readonly viewBox: string;
  readonly paths: ReadonlyArray<string>;
  readonly fillRule?: "evenodd";
}

export const PROVIDER_MARKS: Record<string, ProviderMarkData> = ${JSON.stringify(marks, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`extracted ${Object.keys(marks).length} marks → ${OUT}`);
for (const s of skipped) console.log(`  skipped ${s.id}: ${s.reason}`);
