#!/usr/bin/env bash

# Shared Linux display discovery for interactive previews and Electron E2E.
# A caller-provided desktop always wins. In an Amp orb, command shells do not
# inherit the Desktop session, so recover its generated environment only when
# the live X11 or Wayland socket proves that session still exists.
junto_use_available_desktop() {
  if [[ -n "${DISPLAY:-}" || -n "${WAYLAND_DISPLAY:-}" ]]; then
    return 0
  fi
  if [[ "$(uname -s)" != "Linux" || -z "${AMP_DIRECT_DESKTOP:-}" ]]; then
    return 1
  fi

  local desktop_environment="${HOME}/.cache/amp/desktop/environment"
  if [[ ! -r "$desktop_environment" ]]; then
    return 1
  fi

  # Generated by Amp's Desktop session for this same unprivileged user.
  # shellcheck disable=SC1090
  source "$desktop_environment"

  if [[ -n "${DISPLAY:-}" && "$DISPLAY" == :* ]]; then
    local display_number="${DISPLAY#:}"
    display_number="${display_number%%.*}"
    if [[ -S "/tmp/.X11-unix/X${display_number}" ]]; then
      return 0
    fi
  fi
  if [[ -n "${WAYLAND_DISPLAY:-}" && -n "${XDG_RUNTIME_DIR:-}" && -S "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]]; then
    return 0
  fi

  unset DISPLAY WAYLAND_DISPLAY
  return 1
}
