#!/usr/bin/env bun
// Generates src/renderer/styles/theme.generated.css from the single token
// source (src/shared/theme/). Dark values land in @theme (Tailwind v4
// registers utilities from them); bright overrides ride on
// html[data-theme="bright"]. Run after editing the source: bun run theme:build
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  contrastRatio,
  DARK_RUNTIME,
  semanticTokens,
  TOKEN_NAMES,
  tokenCss,
  themeRuntime,
  FONT_DISPLAY,
  FONT_MONO,
} from "../src/shared/theme";
import { SEMANTIC_BRIGHT_OVERRIDES } from "../src/shared/theme/semantic";

const OUT = resolve(__dirname, "../src/renderer/styles/theme.generated.css");

// The palette the app shipped before tokenization. Dark must keep rendering
// these exact colors; the generator fails loudly if a source edit shifts one.
const LEGACY_DARK_HEX: Record<string, string> = {
  ground: "#0c0b0a",
  raise: "#16130f",
  "raise-2": "#141210",
  inset: "#131110",
  well: "#090807",
  ink: "#ede6da",
  "ink-2": "#c8c0b0",
  dim: "#8a8378",
  faint: "#68604a",
  amber: "#e8a33d",
  "amber-hi": "#f0d9a8",
  cyan: "#39c6d6",
  violet: "#8b7beb",
  crimson: "#e5484d",
  steel: "#8fa3b0",
  indigo: "#6e7bf2",
  gold: "#d4a94f",
  orange: "#f07438",
  green: "#5fb98e",
};

let failed = false;
for (const [name, hex] of Object.entries(LEGACY_DARK_HEX)) {
  const actual = DARK_RUNTIME[name];
  if (actual !== hex) {
    console.error(`DRIFT: dark ${name} = ${actual}, legacy ${hex}`);
    failed = true;
  }
}
if (failed) {
  console.error(
    "Dark mode must stay pixel-identical. Fix the source or, if the change is deliberate, update LEGACY_DARK_HEX.",
  );
  process.exit(1);
}

const dark = semanticTokens("dark");

const lines: string[] = [
  "/* GENERATED by scripts/theme-build.ts from src/shared/theme/ — do not edit.",
  "   Edit the source, then run `bun run theme:build`. */",
  "",
  "@theme {",
  "  /* field + elevation ladder, ink ladder, strokes, overlays, scrims,",
  "     hues, color roles. Dark is the default; bright rides data-theme. */",
];
for (const name of TOKEN_NAMES) {
  lines.push(`  --color-${name}: ${tokenCss(name, dark[name]!)};`);
}
lines.push(
  "",
  "  /* house type: mono instrument + condensed display stamp */",
  `  --font-mono: ${FONT_MONO};`,
  `  --font-display: ${FONT_DISPLAY};`,
  "}",
  "",
  'html[data-theme="bright"] {',
  "  color-scheme: light;",
);
for (const [name, value] of Object.entries(SEMANTIC_BRIGHT_OVERRIDES)) {
  lines.push(`  --color-${name}: ${tokenCss(name, value)};`);
}
lines.push("}", "");

writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${OUT}`);

// Soft contrast report (hard gate lands with the enforcement layer).
console.log("\ncontrast report (informational):");
const report = (mode: "dark" | "bright") => {
  const t = themeRuntime(mode);
  const pairs: Array<[string, string, number]> = [
    ["ink", "ground", 7],
    ["ink-2", "raise", 4.5],
    ["dim", "ground", 4.5],
    ["faint", "ground", 4.5],
    ["amber-fg", "ground", 4.5],
    ["cyan-fg", "ground", 4.5],
    ["crimson-fg", "ground", 4.5],
  ];
  for (const [fg, bg, min] of pairs) {
    const ratio = contrastRatio(t[fg]!, t[bg]!);
    const mark = ratio >= min ? "ok " : "LOW";
    console.log(`  ${mode} ${fg}/${bg}: ${ratio.toFixed(2)} (min ${min}) ${mark}`);
  }
};
report("dark");
report("bright");
