import { sign, verify, type KeyObject } from "node:crypto";
import { canonicalStationBrowserJson, decodeStationBrowserEnvelope, isStationBrowserKeyId, STATION_BROWSER_CLOCK_SKEW_MS, STATION_BROWSER_MAX_TTL_MS, type StationBrowserDenial, type StationBrowserEnvelope, type StationBrowserRequest } from "@shared/station-browser";
import { parseNodeRef } from "@shared/node-ref";

declare const witnessBrand: unique symbol;
export interface AdmittedDelegationWitness { readonly [witnessBrand]: never }
type WitnessData = Readonly<{ kind: "agent-edge" | "operator-ui"; stationId: string; agentRef?: string }>;
const witnesses = new WeakMap<object, WitnessData>();
/** Main-process admission seam: callers must first have passed process-bind plus edge checks. */
export const admitAgentEdgeDelegation = (admitted: Readonly<{ stationId: string; canonicalAgentRef: string }>): AdmittedDelegationWitness => { if (!/^[A-Za-z0-9._:-]+$/.test(admitted.stationId) || !parseNodeRef(admitted.canonicalAgentRef).ok) throw new Error("main admission requires canonical station and agent references"); const witness = {} as AdmittedDelegationWitness; witnesses.set(witness, { kind: "agent-edge", stationId: admitted.stationId, agentRef: admitted.canonicalAgentRef }); return witness; };
/** Main-process UI admission seam. This constructor deliberately has no client principal argument. */
export const admitOperatorUiDelegation = (stationId: string): AdmittedDelegationWitness => { if (!/^[A-Za-z0-9._:-]+$/.test(stationId)) throw new Error("main admission requires a canonical station reference"); const witness = {} as AdmittedDelegationWitness; witnesses.set(witness, { kind: "operator-ui", stationId }); return witness; };
export interface StationBrowserTrust { readonly keyId: string; readonly publicKey: KeyObject; readonly originStationId: string }
export interface StationBrowserVerificationContext { readonly stationId: string; readonly now: number; readonly role: "remote"; readonly browserReady: boolean; readonly resolvePage: (pageRef: string) => Readonly<{ hostId: string; edgeAllowed: boolean; policyAllowed: boolean }> | undefined; readonly currentGeneration: (request: StationBrowserRequest) => string | undefined; readonly allowAction: (request: StationBrowserRequest) => boolean }
export class StationBrowserReplayCache { private readonly values = new Map<string, number>(); constructor(private readonly capacity = 1024) {} consume(key: string, acceptedUntil: number, now: number): "ok" | "replayed" | "capacity" { for (const [k, expiry] of this.values) if (expiry < now) this.values.delete(k); if (this.values.has(key)) return "replayed"; if (this.values.size >= this.capacity) return "capacity"; this.values.set(key, acceptedUntil); return "ok"; } }
const signed = (request: StationBrowserRequest) => Buffer.from(canonicalStationBrowserJson(Object.fromEntries(Object.entries(request).filter(([, value]) => value !== null))));
export const mintStationBrowserEnvelope = (witness: AdmittedDelegationWitness, request: Omit<StationBrowserRequest, "authority" | "originStationId" | "agentRef">, keyId: string, privateKey: KeyObject): StationBrowserEnvelope => { const data = witnesses.get(witness); if (data === undefined) throw new Error("station browser delegation requires a main-admitted witness"); if (!isStationBrowserKeyId(keyId) || privateKey.type !== "private" || privateKey.asymmetricKeyType !== "ed25519") throw new Error("station browser delegation requires an Ed25519 private key and canonical key id"); const bound = { ...request, authority: data.kind, originStationId: data.stationId, agentRef: data.agentRef ?? null, pageRef: request.pageRef ?? null, session: request.session ?? null, payload: request.payload ?? null } as unknown as StationBrowserRequest; return { request: bound, keyId, signature: sign(null, signed(bound), privateKey).toString("base64url") }; };
export const verifyStationBrowserEnvelope = (frame: string, trust: StationBrowserTrust, context: StationBrowserVerificationContext, replays: StationBrowserReplayCache): { readonly ok: true; readonly request: StationBrowserRequest } | { readonly ok: false; readonly denial: StationBrowserDenial } => { const decoded = decodeStationBrowserEnvelope(frame); if (typeof decoded === "string") return { ok: false, denial: decoded }; if (trust.publicKey.asymmetricKeyType !== "ed25519") return { ok: false, denial: "algorithm" }; if (decoded.keyId !== trust.keyId) return { ok: false, denial: "key" }; const r = decoded.request; if (context.role !== "remote" || !context.browserReady || r.originStationId !== trust.originStationId || r.targetStationId !== context.stationId || (r.session !== undefined && r.session.hostId !== context.stationId)) return { ok: false, denial: "wrong_host" }; if (r.expiresAt <= r.issuedAt || r.expiresAt - r.issuedAt > STATION_BROWSER_MAX_TTL_MS) return { ok: false, denial: "ttl" }; if (r.issuedAt > context.now + STATION_BROWSER_CLOCK_SKEW_MS) return { ok: false, denial: "not_yet_valid" }; if (r.expiresAt < context.now - STATION_BROWSER_CLOCK_SKEW_MS) return { ok: false, denial: "expired" }; if (!verify(null, signed(r), trust.publicKey, Buffer.from(decoded.signature, "base64url"))) return { ok: false, denial: "signature" }; if (!context.allowAction(r)) return { ok: false, denial: "forbidden" }; if (r.pageRef !== undefined) { const page = context.resolvePage(r.pageRef); if (page === undefined || page.hostId !== context.stationId) return { ok: false, denial: "stale_canvas" }; if (!page.edgeAllowed || !page.policyAllowed) return { ok: false, denial: "forbidden" }; } if (r.session !== undefined && context.currentGeneration(r) !== r.session.generation) return { ok: false, denial: "stale_generation" }; const replay = replays.consume(`${r.originStationId}:${r.nonce}`, r.expiresAt + STATION_BROWSER_CLOCK_SKEW_MS, context.now); return replay === "ok" ? { ok: true, request: r } : { ok: false, denial: replay }; };
