/**
 * Audit generator for the pre-retirement operator-flags fixture.
 *
 * Writes `flags-v5.db`: a schema-v5 Command Center whose `factory` canvas was
 * authored while operator flags, `flagOnUnsatisfied`, the `flags` verb and
 * pad/sheet `announces` were legal. One task is created through WorkService,
 * so the immutable work log holds rows the migration must not touch.
 *
 * Frozen history: this build cannot regenerate the stored database.
 */
import type { CanvasDoc } from "../../../src/shared/canvas";

const agent = (id: string, x: number, extra: Record<string, unknown> = {}) => ({
  id,
  type: "text" as const,
  text: id,
  x,
  y: 0,
  width: 240,
  height: 72,
  ether: {
    entity: { kind: "agent", name: `local:${id}` },
    terminal: {
      bindingId: `fixture-flags-${id}`,
      launch: { kind: "harness", argv: ["codex"] },
      harness: "codex",
    },
    host: "local",
    ...extra,
  },
});

const node = (id: string, kind: string, x: number, y: number, ether: Record<string, unknown> = {}) => ({
  id,
  type: "text" as const,
  text: id,
  x,
  y,
  width: 200,
  height: 80,
  ether: { entity: { kind }, ...ether },
});

export const FLAGS_FIXTURE_DOC = {
  nodes: [
    // A blocker seat: the mirror law stamps crimson `color: "1"` on save.
    agent("agent", 0, { flags: ["blocker"] }),
    agent("peer", 300, { flags: ["attention", "parked"] }),
    node("tasks", "task", 0, 200, { flags: ["parked"] }),
    node("pad", "pad", 300, 200),
    node("relay", "relay", 600, 200),
    node("cron", "cron", 900, 200, { timer: { expression: "0 9 * * *" } }),
    node("gauge", "watcher", 900, 400, {
      watch: { kind: "stat_threshold", source: "hermes", key: "local:agent", stat: "load", op: "gt", value: 3, flagOnUnsatisfied: true },
    }),
    // A plain note keeps an authored red that no flag stamped.
    { id: "note", type: "text" as const, text: "keep red", x: 0, y: 400, width: 200, height: 80, color: "1" },
  ],
  edges: [
    { id: "claim-edge", fromNode: "tasks", toNode: "agent", ether: { verb: "works" } },
    { id: "agent-announces", fromNode: "agent", toNode: "relay", ether: { verb: "announces" } },
    { id: "task-announces", fromNode: "tasks", toNode: "relay", ether: { verb: "announces" } },
    { id: "pad-announces", fromNode: "pad", toNode: "relay", ether: { verb: "announces" } },
    { id: "relay-wakes", fromNode: "relay", toNode: "peer", ether: { verb: "wakes" } },
    { id: "relay-flags", fromNode: "relay", toNode: "agent", ether: { verb: "flags" } },
    { id: "cron-flags", fromNode: "cron", toNode: "tasks", ether: { verb: "flags" } },
  ],
} as unknown as CanvasDoc;

/** Stored v5 bytes are immutable; current migrations cannot recreate them. */
export const generateFlagsFixture = async (_path: string): Promise<void> => {
  throw new Error("This fixture is frozen history and cannot be regenerated by this build.");
};
